# Generated by Django 3.2.12 on 2022-02-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_api', models.URLField(verbose_name='目标http接口')),
                ('api_request_data', models.TextField(verbose_name='请求内容')),
                ('api_response_data', models.TextField(verbose_name='响应内容')),
            ],
        ),
    ]
